### ISSUE TITLE
Scheme already registered error on Windows

### ISSUE THREAD

**Issue by kevinsawicki** [electronjs/electron-sample#11]
Got this when running the app.

<img width="270" alt="screen shot 2015-08-18 at 4 03 42 pm" src="https://cloud.githubusercontent.com/assets/671378/9345214/91e7b950-45c3-11e5-9532-4461f609fd1f.png">

@paulcbetts you seen this one before? Could it be related to electron compiler?

**Comment by paulcbetts** [comment]
Ya, this is https://github.com/electronjs/electron-compile/issues/19 - Chrome 44 is about to change erry'thing again, so we're just going to switch to that

**Comment by paulcbetts** [comment]
Fixed in 0.8.3
