### ISSUE TITLE
Add an icon for all three platforms

### ISSUE THREAD

**Issue by benogle** [electronjs/electron-sample#8]
It would be cool to have an icon for all three platforms so we can integrate the icon into the build step. People could just replace the icon with their own thing. I suppose we could just use the electron icon. Maybe a different color or style of the electron icon? 

@simurai any ideas? Can be a simple change to the electron icon. Like make it yellow, orange, purple or something.

**Comment by dukex** [comment]
+1 to simple put the electron icon with same color changes


off: please update the electronjs org logo with electron logo ;)

**Comment by simurai** [comment]
How about yellow.. plus some guides. Should give some "in progress" or "replace me" impression.

Mac:
![electron-icon-mac](https://cloud.githubusercontent.com/assets/378023/9347856/376bd748-466a-11e5-99c1-bf2b5a6c405b.png)

Win:
![electron-icon-win](https://cloud.githubusercontent.com/assets/378023/9347858/376f1b4c-466a-11e5-8a04-d6508243ecc0.png)

Linux:
![electron-icon-linux](https://cloud.githubusercontent.com/assets/378023/9347857/376bfdd6-466a-11e5-9d68-6952230ca8c4.png)

**Comment by benogle** [comment]
I dig it

**Comment by simurai** [comment]
Ok, made a PR #12.

> have an icon for all three platforms

Do you mean it can be the same icon or does each platform need a different one?

I kept all icons as circles. Keeps it simple and also noticed that icons on Windows like Chrome or Firefox are circles too. Just those Metro apps are squares. And I think on Linux there isn't really a convention.

**Comment by dukex** [comment]
This issues can be closed
